workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
    scripts:
      - name: Install dependencies
        script: npm install

      - name: Sync Capacitor
        script: npx cap sync ios

      - name: Debug iOS folder
        script: |
          pwd
          ls -la ios/App
          ls -la ios/App/App.xcworkspace
          ls -la ios/App/App.xcodeproj

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App
    artifacts:
      - build/ios/ipa/*.ipa